### PR TITLE
feat: update to rq 1.8

### PR DESCRIPTION
**Pull request by ElPicador**

### CODE REVIEW

**Review by poulainv — APPROVED** [review]
💯

**Review by AdamSelene — APPROVED** [review]

**Comment by Thomas-Mollard** [comment]
I don't see the `empty` method in the [registry](https://github.com/rq/rq/blob/master/rq/registry.py) file, I only see it on the [queue](https://github.com/rq/rq/blob/master/rq/queue.py#L115) 🤔

**Comment by ElPicador** [comment]
> I don't see the `empty` method in the [registry](https://github.com/rq/rq/blob/master/rq/registry.py?rgh-link-date=2021-06-11T12%3A56%3A42Z) file, I only see it on the [queue](https://github.com/rq/rq/blob/master/rq/queue.py?rgh-link-date=2021-06-11T12%3A56%3A42Z#L115) 🤔

:ah: Bad bad pycharm.

**Comment by ElPicador** [comment]
Ok, I tested it locally with a bad hacky way (edit the dep in the virtual env, and port the change here)

**Pull request merged**
